### ISSUE TITLE
UserOperations.removeProduct()

### ISSUE THREAD

**Issue by Niops** [Niops/A10-TeamProject#2]
- [ Issue ]
 Typing an item that is not on productList does nothing.

- [ Does it cause a crash? ]
No. 

- [ More Information/Suspected Cause ]
Typing Eggss instead of Eggs does not remove Eggs. It instead does nothing. There is no input validation. 

- [ Steps Taken to Fix ]
None 

- [ Outcome ]
None

**Comment by Ender1299** [comment]
While not elegant, this change to UserOperations.java's removeProduct method seems to fix the problem:

public void removeProduct(Scanner input, ArrayList<Product> productList)
   {
      System.out.println("Remove Product -");
      System.out.print("Enter Name: ");
      String productName = input.next();
      
      for (Product product : productList)
      {
         if (product.getName().equals(productName))
         { 
           productList.remove(product);
           System.out.println(productName + " Removed");
           break;
         } 
         if (!product.getName().equals(productName))
         {
            System.out.println("Not in the list");
            break;
         }
         
      } 
      
      
   }
